export const Images = {
    user: '/assets/icons/user.svg',
    darkLogo: '/assets/icons/Logo dark 1.svg',
    vector: '/assets/icons/Vector.svg',
    polygon1: '/assets/icons/Polygon 1.svg',
    polygon2: '/assets/icons/Polygon 2.svg',
    farmer1: '/assets/icons/image 12.svg',
    farmer2: '/assets/icons/image 11.svg',
    home: '/assets/icons/home.svg',
    piggi: '/assets/icons/piggi.svg',
    thumbUp: '/assets/icons/thumb-up.svg',
    handHeart: '/assets/icons/hand-Hart.svg',
    rightArrow: '/assets/icons/right-arrow.svg',
    leftArrow: '/assets/icons/arrow-left.svg',
    group1: '/assets/icons/Group 85720.svg',
    group2: '/assets/icons/Group 85726.svg',
    group3: '/assets/icons/Group 85722.svg',
    group4: '/assets/icons/Group 85721.svg',
    vid1: '/assets/icons/Rectangle 274.png',
    
}